import type { Metadata } from 'next';
import '@styles/reset.css';
import '@styles/global.css';
import ThemeRootProvider from '@/components/theme-provider/ThemeProvider';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="tr">
      <body>
        <ThemeRootProvider>{children}</ThemeRootProvider>
      </body>
    </html>
  );
}
