import { notFound } from 'next/navigation';
import type { Metadata } from 'next';
import '@styles/reset.css';
import '@styles/global.css';
import ThemeRootProvider from '@/components/theme-provider/ThemeProvider';

// Can be imported from a shared config
const locales = ['en', 'tr'];

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function LocaleLayout({
  children,
  params: { locale },
}: {
  children: any;
  params: any;
}) {
  // Validate that the incoming `locale` parameter is valid
  if (!locales.includes(locale as any)) notFound();

  return (
    <html lang={locale}>
      <body>
        <ThemeRootProvider>{children}</ThemeRootProvider>
      </body>
    </html>
  );
}
